### PR TITLE
Fix official 7" touchscreen config mode

### PR DESCRIPTION
**Pull request by dridri**
Comes along with https://github.com/ayufan-pine64/linux-pine64/pull/3, which adds "gt911_DB2" config mode.

### CODE REVIEW

**Comment by ayufan** [comment]
Lets remove that .dtb's completly. They should be compiled when required.

**Comment by dridri** [comment]
Agreed

**Comment by ayufan** [comment]
But you also have to fix scripts to compile it.

**Comment by dridri** [comment]
Hmm it already works I think. Let me re-check

**Comment by dridri** [comment]
Now it does :)

**Comment by ayufan** [comment]
@dridri 

Can you also add `.gitignore` for these files?

**Comment by ayufan** [comment]
Thanks!

**Comment by dridri** [comment]
Have you tested it ? I'm not sure if I forget something somewhere else (I did a lot modifications to other things locally)
Edit: I said nothing, I forget that you still have no touchscreen in hands

**Comment by ayufan** [comment]
Exactly. I can't test it yet.

**Pull request merged**
